apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qzluwkygy-python 
  janus-idp.io/tekton: qzluwkygy-python
  backstage.io/kubernetes-id: qzluwkygy-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qzluwkygy-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml